# Tensors 

In [5]:
import torch

## zeros()

In [8]:
a = torch.zeros(4,3)

## size() and shape

In [10]:
a.size()

torch.Size([4, 3])

## randn() and randn_like()

In [11]:
a = torch.randn(4,3)

In [12]:
a

tensor([[-2.0659,  0.9546,  0.2433],
        [-0.4682,  0.6863, -1.1336],
        [-0.8039,  2.0927, -1.2353],
        [-1.9786,  0.7901, -0.7838]])

## fill_()

In [19]:
a.fill_(1)
a

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

## view()

In [20]:
a

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [21]:
t = a.view(3,4)

In [22]:
t

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

## numpy()

In [23]:
# tensor to numpy easy
a.numpy()

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)